title: Tushar Pankaj
email: tushar.s.pankaj@gmail.com
description: Originally a blog about my deep learning research. Now a blog about my life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tspankaj.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tushar_pankaj
github_username:  tpankaj
author: Tushar Pankaj

# Compress sass
sass:
    style: compressed

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - vendor

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
